# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ED5AKpfjRb9cxqNmCBpFhQGY9aVkYPdZ
"""

import pickle
from matplotlib import pyplot as plt

lt=pickle.load(open('/content/fileevo.pkl','rb'))
print(lt)

fnl=lt[4:]
fnl

fl=[]
for i in fnl:
  fl.append(float(i))

x=[]
for i in range(len(fnl)):
  x.append(i)

plt.plot(fl)
plt.xlabel('Timestamps')
plt.ylabel('Distance(in metres)')
plt.title('Distance of objects from EVO')
plt.grid(True)
plt.show()